In [2]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv("Products.csv")
df1.head(10)

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio
5,6,Contoso 2G MP3 Player E200 Black,Contoso,Black,$11.00,$21.57,101,MP4&MP3,1,Audio
6,7,Contoso 2G MP3 Player E200 Blue,Contoso,Blue,$11.00,$21.57,101,MP4&MP3,1,Audio
7,8,Contoso 4G MP3 Player E400 Silver,Contoso,Silver,$30.58,$59.99,101,MP4&MP3,1,Audio
8,9,Contoso 4G MP3 Player E400 Black,Contoso,Black,$30.58,$59.99,101,MP4&MP3,1,Audio
9,10,Contoso 4G MP3 Player E400 Green,Contoso,Green,$30.58,$59.99,101,MP4&MP3,1,Audio

In [4]:
# clean whitespace and formatting the headeres

df1.columns = df1.columns.str.lower().str.strip().str.replace(" ", "_")
df1.columns

Index(['productkey', 'product_name', 'brand', 'color', 'unit_cost_usd',
       'unit_price_usd', 'subcategorykey', 'subcategory', 'categorykey',
       'category'],
      dtype='str')

In [5]:
# remove unwanted characters from column values

colms = ["product_name", "brand"]

for i in colms:
    df1[i] = (
        df1[i].str.replace(r"^[A-Z]\.\s*","", regex=True).str.strip()
    )

In [6]:
df1.iloc[1000:1030]

,productkey,product_name,brand,color,unit_cost_usd,unit_price_usd,subcategorykey,subcategory,categorykey,category
1000,1001,Datum Rangefinder Digital Camera X200 Orange,Datum,Orange,$66.26,$200.00,401,Digital Cameras,4,Cameras and camcorders
1001,1002,Datum Slim Digital Camera M180 Orange,Datum,Orange,$68.06,$148.00,401,Digital Cameras,4,Cameras and camcorders
1002,1003,Datum Ultra Compact Digital Camera M190 Orange,Datum,Orange,$75.88,$165.00,401,Digital Cameras,4,Cameras and camcorders
1003,1004,Datum All in One Digital Camera M200 Orange,Datum,Orange,$86.45,$188.00,401,Digital Cameras,4,Cameras and camcorders
1004,1005,Datum Interchangeable lens Non-SLR Digital Cam...,Datum,Orange,$88.79,$268.00,401,Digital Cameras,4,Cameras and camcorders
1005,1006,Datum Super-zoom Digital Camera X300 Orange,Datum,Orange,$96.08,$290.00,401,Digital Cameras,4,Cameras and camcorders
1006,1007,Datum Consumer Digital Camera E100 Orange,Datum,Orange,$143.26,$281.00,401,Digital Cameras,4,Cameras and camcorders
1007,1008,Datum Consumer Digital Camera M300 Orange,Datum,Orange,$84.84,$184.50,401,Digital Cameras,4,Cameras and camcorders
1008,1009,Datum Advanced Digital Camera M300 Orange,Datum,Orange,$86.68,$188.50,401,Digital Cameras,4,Cameras and camcorders
1009,1010,Datum Bridge Digital Camera M300 Orange,Datum,Orange,$85.95,$186.90,401,Digital Cameras,4,Cameras and camcorders
1010,1011,Datum SLR-like Digital Camera M400 Orange,Datum,Orange,$90.55,$196.90,401,Digital Cameras,4,Cameras and camcorders
1011,1012,Datum Point Shoot Digital Camera M500 Orange,Datum,Orange,$91.05,$198.00,401,Digital Cameras,4,Cameras and camcorders
1012,1013,Datum Full Frame Digital Camera X300 Orange,Datum,Orange,$76.53,$231.00,401,Digital Cameras,4,Cameras and camcorders
1013,1014,Datum Compact Digital Camera M200 Green,Datum,Green,$59.32,$129.00,401,Digital Cameras,4,Cameras and camcorders
1014,1015,Datum Rangefinder Digital Camera X200 Green,Datum,Green,$66.26,$200.00,401,Digital Cameras,4,Cameras and camcorders
1015,1016,Datum Slim Digital Camera M180 Green,Datum,Green,$68.06,$148.00,401,Digital Cameras,4,Cameras and camcorders
1016,1017,Datum Ultra Compact Digital Camera M190 Green,Datum,Green,$75.88,$165.00,401,Digital Cameras,4,Cameras and camcorders
1017,1018,Datum All in One Digital Camera M200 Green,Datum,Green,$86.45,$188.00,401,Digital Cameras,4,Cameras and camcorders
1018,1019,Datum Interchangeable lens Non-SLR Digital Cam...,Datum,Green,$88.79,$268.00,401,Digital Cameras,4,Cameras and camcorders
1019,1020,Datum Super-zoom Digital Camera X300 Green,Datum,Green,$96.08,$290.00,401,Digital Cameras,4,Cameras and camcorders
1020,1021,Datum Consumer Digital Camera E100 Green,Datum,Green,$143.26,$281.00,401,Digital Cameras,4,Cameras and camcorders
1021,1022,Datum Consumer Digital Camera M300 Green,Datum,Green,$84.84,$184.50,401,Digital Cameras,4,Cameras and camcorders
1022,1023,Datum Advanced Digital Camera M300 Green,Datum,Green,$86.68,$188.50,401,Digital Cameras,4,Cameras and camcorders
1023,1024,Datum Bridge Digital Camera M300 Green,Datum,Green,$85.95,$186.90,401,Digital Cameras,4,Cameras and camcorders
1024,1025,Datum SLR-like Digital Camera M400 Green,Datum,Green,$90.55,$196.90,401,Digital Cameras,4,Cameras and camcorders
1025,1026,Datum Point Shoot Digital Camera M500 Green,Datum,Green,$91.05,$198.00,401,Digital Cameras,4,Cameras and camcorders
1026,1027,Datum Full Frame Digital Camera X300 Green,Datum,Green,$76.53,$231.00,401,Digital Cameras,4,Cameras and camcorders
1027,1028,Datum Compact Digital Camera M200 Azure,Datum,Azure,$59.32,$129.00,401,Digital Cameras,4,Cameras and camcorders
1028,1029,Datum Rangefinder Digital Camera X200 Azure,Datum,Azure,$66.26,$200.00,401,Digital Cameras,4,Cameras and camcorders
1029,1030,Datum Slim Digital Camera M180 Azure,Datum,Azure,$68.06,$148.00,401,Digital Cameras,4,Cameras and camcorders

In [7]:
# remove $ from price related columns

mony_col = ["unit_cost_usd", "unit_price_usd"]

for i in mony_col:
    df1[i] = (
        df1[i].str.replace("$","", regex=False).str.replace(",","", regex=False)
    )
    df1[i]= pd.to_numeric(df1[i], errors="coerce")

In [8]:
df1.iloc[1950:1960]

,productkey,product_name,brand,color,unit_cost_usd,unit_price_usd,subcategorykey,subcategory,categorykey,category
1950,1951,Litware Refrigerator 24.7CuFt X980 Silver,Litware,Silver,1060.22,3199.99,802,Refrigerators,8,Home Appliances
1951,1952,Litware Refrigerator 19CuFt M760 Silver,Litware,Silver,413.42,899.00,802,Refrigerators,8,Home Appliances
1952,1953,Litware Refrigerator 9.7CuFt M560 Silver,Litware,Silver,226.71,493.00,802,Refrigerators,8,Home Appliances
1953,1954,Litware Refrigerator 4.6CuFt E280 Silver,Litware,Silver,152.94,299.99,802,Refrigerators,8,Home Appliances
1954,1955,Litware Refrigerator 3.2CuFt E160 Silver,Litware,Silver,142.75,279.99,802,Refrigerators,8,Home Appliances
1955,1956,Litware Refrigerator 1.7CuFt E120 Silver,Litware,Silver,66.27,129.99,802,Refrigerators,8,Home Appliances
1956,1957,Litware Refrigerator 24.7CuFt X980 Green,Litware,Green,1060.22,3199.99,802,Refrigerators,8,Home Appliances
1957,1958,Litware Refrigerator 19CuFt M760 Green,Litware,Green,413.42,899.00,802,Refrigerators,8,Home Appliances
1958,1959,Litware Refrigerator 9.7CuFt M560 Green,Litware,Green,226.71,493.00,802,Refrigerators,8,Home Appliances
1959,1960,Litware Refrigerator 4.6CuFt E280 Green,Litware,Green,152.94,299.99,802,Refrigerators,8,Home Appliances

In [9]:
# saved csv file in local folder

df1.to_csv("updated_data/Product1.csv", index=False)

In [10]:
import pandas as pd
import numpy as np

In [11]:
df_sal = pd.read_csv("Sales.csv")
df_sal

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD
...,...,...,...,...,...,...,...,...,...
62879,2243030,1,2/20/2021,NaN,1216913,43,632,3,USD
62880,2243031,1,2/20/2021,2/24/2021,511229,0,98,4,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

In [12]:
# update the column names and remove space and replace it with "_", it will be easy while using this data into SQL

df_sal.columns = df_sal.columns.str.lower().str.strip().str.replace(" ", "_")

In [ ]:
# change the order_date and delivery_date format is not correct, so update the format to datetime

date_col = ["order_date", "delivery_date"]

for i in date_col:
    df_sal[i] = (
        df_sal[i].str.strip()
    )
    df_sal[i] = pd.to_datetime(df_sal[i], errors="coerce")

In [14]:
df_sal.head(10)

,order_number,line_item,order_date,delivery_date,customerkey,storekey,productkey,quantity,currency_code
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD
5,366002,3,2016-01-01,2016-01-12,266019,0,1080,4,CAD
6,366004,1,2016-01-01,NaT,1107461,38,163,6,GBP
7,366004,2,2016-01-01,NaT,1107461,38,1529,2,GBP
8,366005,1,2016-01-01,NaT,844003,33,421,4,EUR
9,366007,1,2016-01-01,NaT,2035771,43,1617,1,USD

In [ ]:
# checking the null values

print("Invalid Dates:", df_sal["delivery_date"].isna().sum())

Invalid Dates: 49719

In [ ]:
# checking total number of rows we have in data also how many rows of delivery_date column is having empty cell

print("Total rows:", len(df_sal))
print("Missing delivery date:", df_sal["delivery_date"].isna().sum())

Total rows: 62884
Missing delivery date: 49719

In [ ]:
# hear we are checking % of missing values of the total data, and found 79.06% of the data is not having the any value in delivery_date column

missing_perc = df_sal["delivery_date"].isna().mean() * 100
print("missinge per%: ", round(missing_perc, 2))

missinge per%:  79.06

In [ ]:
# we are checking number of orders placed by the order_number and how many of those order numbers are not having the delivery date

order_check = (
    df_sal.groupby("order_number")
    .agg(
        total_lines = ("line_item", "count"),
        missing_delivery = ("delivery_date", lambda x: x.isna().sum())
    )
)

print(order_check.head(20))

              total_lines  missing_delivery
order_number
366000                  1                 1
366001                  2                 0
366002                  3                 0
366004                  2                 2
366005                  1                 1
366007                  2                 2
366008                  3                 3
366009                  1                 1
366010                  1                 0
366011                  4                 4
366012                  3                 3
366013                  1                 1
366014                  2                 0
366016                  1                 1
367000                  1                 1
367003                  1                 1
367004                  2                 2
367005                  7                 0
367006                  1                 1
367007                  2                 2

In [ ]:
# like in previous code we found that there are some order which has the delivery dates, for ex. if one order number is having 3 products
# so out of those 3, 2 products are having the delivery date, so here we are checking how many order_number are not having the delivery date

fully_missing_orders = (
    order_check["total_lines"] == order_check["missing_delivery"]
).sum()

print("Order with completely missing with delivery date: ", fully_missing_orders)

Order with completely missing with delivery date:  20746

In [ ]:
# here we are checking how many orders are having the delivery date

orders_with_delivery= (
    order_check["missing_delivery"] < order_check["total_lines"]
).sum()

print("orders with delivery date: ", orders_with_delivery)

orders with delivery date:  5580

In [ ]:
# in thise we are getting same information, but in different way

order_check["delivery_status"] = "Partial"

order_check.loc[
    order_check["missing_delivery"] == order_check["total_lines"],
    "delivery_status"
] = "All Missing"

order_check.loc[
    order_check["missing_delivery"] == 0,
    "delivery_status"
] = "All available"

print(order_check["delivery_status"].value_counts())

delivery_status
All Missing      20746
All available     5580
Name: count, dtype: int64

In [ ]:
# here we are checking the date range of missing delivery dates and available deliery date

order_check = order_check.reset_index()

order_with_date = df_sal.merge(
    order_check[["order_number", "delivery_status"]],
    on= "order_number",
    how= "left"
)

print(
    order_with_date.groupby("delivery_status")["order_date"]
    .agg(["min", "max", "count"])
)

                       min        max  count
delivery_status
All Missing     2016-01-01 2021-02-20  49719
All available   2016-01-01 2021-02-20  13165

In [ ]:
# here we are checking in which year how many orders delivered and how many not delivered

print(
    order_with_date
    .groupby(
        [order_with_date["order_date"].dt.year, "delivery_status"]
    )
    .size()
)

order_date  delivery_status
2016        All Missing         5744
            All available       1161
2017        All Missing         6396
            All available       1546
2018        All Missing        11244
            All available       2944
2019        All Missing        16917
            All available       4694
2020        All Missing         8539
            All available       2487
2021        All Missing          879
            All available        333
dtype: int64

In [ ]:
# we are checking the same information in %

year_delivery = pd.crosstab(
    order_with_date["order_date"].dt.year,
    order_with_date["delivery_status"],
    normalize= "index"
) * 100

print(year_delivery.round(2))

delivery_status  All Missing  All available
order_date
2016                   83.19          16.81
2017                   80.53          19.47
2018                   79.25          20.75
2019                   78.28          21.72
2020                   77.44          22.56
2021                   72.52          27.48

In [ ]:
# we have created another column which give me the True and False status of delivery date status, if order_number is not having the delivery date
# it will give me False and if has then it will give me True
df_sal["delivery_date_available"] = (
    df_sal["delivery_date"].notna()
)

In [ ]:
# same information getting as available and missing in different column

df_sal["delivery_date_status"] = df_sal["delivery_date"].notna().map({
    True: "Available",
    False: "Missing"
})

In [ ]:
# here we can see the update sales data
df_sal.head(10)

,order_number,line_item,order_date,delivery_date,customerkey,storekey,productkey,quantity,currency_code,delivery_date_available,delivery_date_status
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD,False,Missing
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD,True,Available
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD,True,Available
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD,True,Available
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD,True,Available
5,366002,3,2016-01-01,2016-01-12,266019,0,1080,4,CAD,True,Available
6,366004,1,2016-01-01,NaT,1107461,38,163,6,GBP,False,Missing
7,366004,2,2016-01-01,NaT,1107461,38,1529,2,GBP,False,Missing
8,366005,1,2016-01-01,NaT,844003,33,421,4,EUR,False,Missing
9,366007,1,2016-01-01,NaT,2035771,43,1617,1,USD,False,Missing

In [38]:
df_sal.to_csv("updated_data/Sales1.csv", index= False)